version: 2.1

jobs:
  build:
    docker:
      - image: esolang/lolcode:latest
    steps:
      - checkout
      - run: cat hello.lolcode
      - run: lolcode hello.lolcode

workflows:
  workflow1:
    jobs:
      - build
 
